### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by nitrix** [mxgmn/WaveFunctionCollapse#2]
Please chose a license for the good of the open-source community (:

As it currently stand, albeit very nice, this tremendous amount of work cannot be incorporated into other research / products / etc. That's because in many countries, unlicensed work belongs by copyright laws to its original author.

Something like MIT would probably be ideal. Your name will be kept, but we'll all be able to use it for our own purposes.

Edit: I just noticed you put blocks within your sources, but a LICENSE file would still be better.

Cheers.

**Comment by lemtzas** [comment]
It's apparently MIT. https://github.com/mxgmn/WaveFunctionCollapse/blob/master/Main.cs

**Comment by tomisme** [comment]
The author [said on hackernews](https://news.ycombinator.com/item?id=12612246) that there is no LICENSE file because there are samples in the repo with unknown licenses.

**Comment by mxgmn** [comment]
@tomisme Yeah, thank you. But it seems that LICENSE files became a tradition, and traditions are as important as laws, so I'll just write in that file which files are licensed and which are not.

**Comment by abetusk** [comment]
@mxgmm, you might want to mention that each source file should be checked for the license they're under as they're under different or unknown licenses and that most (?) of them are under an MIT license.  Obviously the individual files should be checked for their respective license but it's nice from a casual observer point of view to know that the project is "mostly" free/libre/open source.

**Comment by mxgmn** [comment]
@abetusk Thanks. Done.

Closing.
