### ISSUE TITLE
How can i try 3d mode?

### ISSUE THREAD

**Issue by kintovt** [mxgmn/WaveFunctionCollapse#23]

**Comment by mxgmn** [comment]
This repo contains only 2d models, 3d models will be in a different repo later.

**Comment by usernameak** [comment]
@mxgmn When later

**Comment by mxgmn** [comment]
@usernameak Some basic 3d version with text output - this week. Full 3d repo including generation of Minecraft levels - not soon, I'm working on generalizing WFC in a different direction now.

**Comment by Asmageddon** [comment]
What is the different direction, if I may ask?

**Comment by mxgmn** [comment]
@Asmageddon Secret! =)
