### ISSUE TITLE
Support JSON Config Files (like the C++ ver.)

### ISSUE THREAD

**Issue by VelocityRa** [mxgmn/WaveFunctionCollapse#28]
Someone moving to the [C++ version](https://github.com/emilk/wfc) (for speed, perhaps) shouldn't have to port their config files to the format supported by that version.

JSON support is currently beeing implemented for that version ([Issue/Discussion](https://github.com/emilk/wfc/issues/2)) and I'll implement it here as well so that there's some common ground between the 2 versions. We've currently agreed to [this](https://github.com/emilk/wfc/blob/json/samples.json) or ([this](https://cloud.githubusercontent.com/assets/6632271/19219787/ad9af04e-8e25-11e6-9bdd-6ccc21f61678.png), fomatted differently) format. Any objections?

**Comment by mxgmn** [comment]
No objections. Since the standard library doesn't support JSON, if you make this PR I'll leave it open like the command line one for people to merge in their forks.

**Comment by VelocityRa** [comment]
[But it does support JSON](http://stackoverflow.com/a/24891561). I'm planning to use the first method, which is even more compatible.

**Comment by mxgmn** [comment]
Oh, didn't know this, will consider JSON in future projects then. JSON PR is welcome, but I'll still leave it open since I don't want to support multiple branches.

**Comment by VelocityRa** [comment]
Not sure what you mean by support multiple branches. *I'm* gonna handle the JSON parsing in my PR.
Also, if I'm not mistaken, the only file that needs to change is `Main.cs` (currently less than 60 LoC).

**Comment by mxgmn** [comment]
If I add/remove examples or parameters, I would have to modify JSON parsing also.

**Comment by VelocityRa** [comment]
Ah, I guess that makes sense.
Well, the goal for this was for people to actually use it, not make it harder by forcing them to either fork + merge the PR or paste the changes manually. This goes for the other unmerged PR as well, I doubt the vast majority of people using WFC know about it, let alone go through the trouble of using it.

Anyway, I'll talk with the other dev about the possibility of adding XML support to the C++ version as I originally intended.

**Comment by mxgmn** [comment]
I'll link this command line PR from the readme then.

**Comment by VelocityRa** [comment]
Yeah that would be better. Might also want to include Install/Build instructions or at least link to the relevant Issue while you're at it.

**Comment by mxgmn** [comment]
Yes, I'm going to.
