### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by buckle2000** [mxgmn/WaveFunctionCollapse#30]
WTF is this?
https://github.com/mxgmn/WaveFunctionCollapse/blob/6c1481c2aa42cb443ff44727cdd5c24312d67207/Model.cs#L101

**Comment by mxgmn** [comment]
This is an extension method defined in Stuff.cs. It returns a random index of an array according to a probability distribution in that array.

**Comment by buckle2000** [comment]
Thanks!
