### ISSUE TITLE
No longer able to compile using Visual Studio Community / .net Framework

### ISSUE THREAD

**Issue by tyronx** [mxgmn/WaveFunctionCollapse#32]
Is this a mono framework only feature or something?

![compileerror](https://user-images.githubusercontent.com/762006/29753272-fbda5470-8b6d-11e7-8d50-e8460efbb16f.png)

**Comment by mxgmn** [comment]
It's a C# 7.0 notation. You can either change this to Func<> (see how it was in the previous commits) or use a compiler version that supports 7.0, it's enabled in VS 2017 by default.
