### ISSUE TITLE
I tried to solve the problem with constraints, but there are too many failures. Is this normal?

### ISSUE THREAD

**Issue by greentec** [mxgmn/WaveFunctionCollapse#38]
Hello!
Thanks for great algorithm, I saw this stuff on reddit and following until nowadays. 
Recently, I tried your algorithm with fast-wfc (but you added this with your repo too), and I found this is very fast but also memory-consuming. For make bigger map, I got out-of-memory error.
So I tried make many maps like grid, and patch them together. So I tried to solve the problem with constraints (predefined patterns with up and left line) with same model, but there were too many failures. It succeeds at all.
So my question is, is this normal? I wonder if you have a lot of failures under these constraints. Thanks for advance!

(For reference, number of patterns of my data is around 8,000)

**Comment by greentec** [comment]
Never mind.. I got some miss.

**Comment by mxgmn** [comment]
8000 patterns is quite a lot. For such inputs, [texture synthesis](https://en.wikipedia.org/wiki/Texture_synthesis) should do a better job, though you lose the (C1) condition. I have some algorithms in [another repo](https://github.com/mxgmn/SynTex). My hardest WFC example (3Bricks.png) has 423 patterns, and most have <128.

**Comment by greentec** [comment]
@mxgmn Thank you for your advice. I will check [SynTex](https://github.com/mxgmn/SynTex)! Actually, I was still getting some failing because of many patterns..
