### ISSUE TITLE
If overlapping model is on 3D, empty pattern and whole pattern (pattern with full same voxels) dominates all.

### ISSUE THREAD

**Issue by greentec** [mxgmn/WaveFunctionCollapse#41]
Hello!
I'm trying 3D version of Overlapping Model, but I met this issue. In many cases, empty pattern (with no voxel) and whole pattern (with full same voxels) dominates all. I cut off the weights to 1, but I thought this is not the best answer. Because almost every building or object has empty pattern and full pattern. So it's natural, but hard to get naturalness.
So did you tried any density function for stationary on Overlapping Model on 3D?

**Comment by mxgmn** [comment]
Hi! What's your input?

One way to introduce densities is to weight colors, then compute pattern weights by multiplying corresponding color weights.

**Comment by greentec** [comment]
Oh, that's a good approach. I will try it. My input is your 'SeaVillas' model. I'm trying to merge all models into one .vox file, and translate that to unique voxel (5x5x5 -> 1x1x1). And then apply overlapping model, finally translate voxel to original pattern (1x1x1 -> 5x5x5).
