### ISSUE TITLE
Usage in a Game

### ISSUE THREAD

**Issue by SneakyTactician** [mxgmn/WaveFunctionCollapse#42]
Hi,

I'm interested in using your project in a game called [Magical Life](https://github.com/SneakyTactician/MagicalLife). Is there a Nuget package of your project, or some way I can incorporate it into my game? Does your project's license allow for usage in a game?

Thanks,
SneakyTactician

**Comment by mxgmn** [comment]
Hi!

No Nuget.

Yes, you can use the code in a game, it's under MIT license.

**Comment by SneakyTactician** [comment]
Okay, Thanks!
