### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by lodenrogue** [mxgmn/WaveFunctionCollapse#45]
I see a Kotlin implementation but it would be nice to have a pure Java implementation.

**Comment by mxgmn** [comment]
I agree.

**Comment by GameplayJDK** [comment]
I'm currently working on a java port. You can find it [here](https://github.com/GameplayJDK/java-wfc).

For now I only managed to port the algorithm to java, but it does not yet support textures, as I plan to use it as a generic starting point for different types of projects. That's also why I did not follow the approach of creating an abstract base class, which can be extended by concrete implementations.
