### ISSUE TITLE
[not an issue] using this algorithm in a game engine plug-in

### ISSUE THREAD

**Issue by ericoporto** [mxgmn/WaveFunctionCollapse#55]
Good day,

I added this algorithm, using the implementation  [fast-wfc](https://github.com/math-fehr/fast-wfc) from Mathieu Fehr and Nathanaël Courant, as a plug-in to be used with Adventure Game Studio:

https://github.com/ericoporto/agsfastwfc

![example_demo_game (1)](https://user-images.githubusercontent.com/2244442/63858107-4c504480-c97b-11e9-9e67-2a848eca39b9.gif)

I haven't added full API yet because I got into some other stuff, but wanted to say thanks on creating this algorithm because I think it will be very useful to procedurally generate content in games. I talked with Mathieu about and he told me maybe you would like to be notified about it too :)

 You can close this.

**Comment by mxgmn** [comment]
Cool!
