### ISSUE TITLE
Can't run it on Mac OS

### ISSUE THREAD

**Issue by mlevin77** [mxgmn/WaveFunctionCollapse#63]
I am trying to run it on Mac OS (10.13). I've downloaded the dotnet and installed it as indicated on the main page of this package. I then run with

% ./dotnet run ~/Desktop/WaveFunctionCollapse-master/WaveFunctionCollapse.csproj --project ~/Desktop/WaveFunctionCollapse-master/

  and I see:

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.3 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.13-x64

but that URL lists only Windows and Linux versions. How is the Mac version of dotnet supposed to run this if it needs something that doesn't exist for Mac?  Apologies, I know nothing about the dotnet world... Am a biologist with background in C and Unix from many years back... What am I doing wrong?

**Comment by kchapelier** [comment]
Try downloading the 2.1 SDK from this link instead: https://dotnet.microsoft.com/download/dotnet-core/2.1

You might also try using Mono instead, it's personnally what I used to make it run on macOS Sierra. There are two issues with information about this : https://github.com/mxgmn/WaveFunctionCollapse/issues/39#issuecomment-428410275 & https://github.com/mxgmn/WaveFunctionCollapse/issues/3

**Comment by mlevin77** [comment]
I installed the 2.1 SDK and I get:

% /usr/local/share/dotnet/dotnet run WaveFunctionCollapse.csproj 
< Chess

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libgdiplus': The specified module could not be found.
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromFile(String filename, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at OverlappingModel..ctor(String name, Int32 N, Int32 width, Int32 height, Boolean periodicInput, Boolean periodicOutput, Int32 symmetry, Int32 ground) in /Users/mlevin/Desktop/WaveFunctionCollapse-master/OverlappingModel.cs:line 27
   at Program.Main() in /Users/mlevin/Desktop/WaveFunctionCollapse-master/Main.cs:line 29

**Comment by mlevin77** [comment]
update. I installed Brew and did "$ brew install mono mono-libgdiplus" and now it seems to work. But

run WaveFunctionCollapse.csproj

processes all of the supplied examples.  Is there a manual somewhere that explains how to create my own example and have it make the tilemap?

**Comment by mxgmn** [comment]
You need to describe the tileset like [this](https://github.com/mxgmn/WaveFunctionCollapse/blob/master/samples/Summer/data.xml) and then link it from samples.xml. You can comment out other examples there.
