### ISSUE TITLE
Deadlock when collapsing

### ISSUE THREAD

**Issue by 1Hyena** [mxgmn/WaveFunctionCollapse#64]
This is not directly related to this particular implementation of WFC but more of a theoretical and a general problem. Recently I started developing my own implementation of WFC that operates on an unbounded output and tolerates contradictions (algorithm does not stop at a contradiction but instead provides contradictions as part of the solution). While my algorithm is generally working as expected and I am happy with its results, there are certain edge cases where the Shannon entropy heuristic causes a valid non-controversial deadlock to happen (see gliders in Conway's Game of Life). It is not a contradiction but the output is garbage for all practical purposes because the distribution of tiles in the output does not reflect the distribution of the respective tiles in the input at all. You can imagine two lines of certain tiles extending themselves into infinity as they mutually enforce each other. A typical oscillation loop.

Please help me brainstorm for ideas how to overcome this artifact. If I don't get any better ideas then I'm going to deal with this as oscillations are typically dealt with in engineering --- by adding random noise. I would make sure that the output is randomly observed a small distance away from the area that is currently being processed according to the Shannon entropy heuristic. As a result the whole output is scattered with occasional single observations, which would act as an obstacle to the Shannon entropy heuristic. I'm in a situation where a contradiction is the lesser evil than the deadlock.

**Comment by mxgmn** [comment]
Could you give an example of this behavior? The choice of a pattern is still random, even with a deterministic heuristic.

**Comment by 1Hyena** [comment]
Yes, sure. I made a bunch of screenshots. I hope this explains the situation.

This is the input:
![archetype](https://user-images.githubusercontent.com/3479475/80211203-f1700980-863d-11ea-8919-8c300c4f8925.jpg)

This is the expected output (you can see contradictions as empty tiles surrounded by question marks):
![expected](https://user-images.githubusercontent.com/3479475/80211205-f208a000-863d-11ea-8380-f68ab75d68fc.jpg)

And here is how the the deadlock happens typically:
![deadlock-1](https://user-images.githubusercontent.com/3479475/80211214-f46afa00-863d-11ea-95af-e80f29624b9c.jpg)

![deadlock-2](https://user-images.githubusercontent.com/3479475/80211212-f3d26380-863d-11ea-87c9-08b0fab0ba0b.jpg)

![deadlock-3](https://user-images.githubusercontent.com/3479475/80211211-f339cd00-863d-11ea-8ffe-7e014090bf89.jpg)

![deadlock-4](https://user-images.githubusercontent.com/3479475/80211208-f2a13680-863d-11ea-965e-b3445c042991.jpg)

![deadlock-5](https://user-images.githubusercontent.com/3479475/80211206-f208a000-863d-11ea-9b47-75418f753d12.jpg)

**Comment by 1Hyena** [comment]
@mxgmn no explanation why closing?

**Comment by mxgmn** [comment]
Because I don't have anything to add to what you wrote.
