### ISSUE TITLE
"Voxel models generated with WFC and other algorithms will be in a separate repo."

### ISSUE THREAD

**Issue by Schizo** [mxgmn/WaveFunctionCollapse#65]
That's an excerpt from the readm, in which repo are the voxel models?

**Comment by mxgmn** [comment]
Still working on it! Screenshots are on [twitter](https://twitter.com/ExUtumno/status/1141354217774428160).

**Comment by StonerDude** [comment]
I wish to appeal this. This needs to be re-opened.
