### ISSUE TITLE
Implementation in C

### ISSUE THREAD

**Issue by woocashh** [mxgmn/WaveFunctionCollapse#67]
Hi Maxim,

This is not an issue to your repo, but I do not have Twitter, and so no other way to contact you.

We are a group of first years from Imperial College London. Strongly inspired by your repo, we have made a simple implementation of WFC in C. If you are interested please have a look:

https://github.com/ic-pcg/waveFunctionCollapse

Thank you for your amazing repo, it was most helpful!

**Comment by mxgmn** [comment]
Hi, Lukasz. I linked it!

**Comment by woocashh** [comment]
Thank you!
