### ISSUE TITLE
Unable to get the program to work in Windows 10

### ISSUE THREAD

**Issue by Orangery-DS** [mxgmn/WaveFunctionCollapse#74]
Hello - I have installed 'dotnet sdk' but cannot get the 'dotnet run --configuration Release WaveFunctionCollapse.csproj' command line to work.  Any advice?  Thank you.

**Comment by masonwheeler** [comment]
"It doesn't work" is not a particularly useful error report.  All that means is "it's doing something other than what I expect it to do."  But if you don't say what it's doing or what you expect, that gives the people who read the error report literally nothing to go on.

Could you explain what you expect it to do and what it's actually doing instead?  For example, if it displays an error message, what is the message?

**Comment by Orangery-DS** [comment]
I appreciate you getting back to me.

Yes, I agree, the information I gave you was not much use.  It's just that I spent a couple of frustrating hours trying to get WFC to run.  It meant installing large files such as 'GitHubDestop', '.Net', 'Visual Studio' and 'GitBash'.  YouTube videos weren't that much help either.

Anyhow, I remember now, that I could not get DotNet (.Net) to launch at all.  Perhaps I should try a re-install, as a repair did not work (no error messages, just a flash).  With Visual Studio, I would follow written suggestions online on how to run a project from GitHub but right clicking on files did not give me the same pull down menus, so got no further.  GitBash seemed too long winded and confusing.

I still hope to get WFC to run, as the program looks fascinating.  I was hoping I could experiment with it and import some of my own 8-bit pixel drawings.  Does this help?  

Regards - Dave S.

**Comment by mxgmn** [comment]
Hi! What happens when you run `dotnet run --configuration Release WaveFunctionCollapse.csproj`?

You don't need GitHub Desktop, Visual Studio or GitBash to run it, only .Net.

**Comment by Orangery-DS** [comment]
That's just it - I couldn't get .Net to launch at all.  I only downloaded and installed other programs as a last resort.  However, I do now remember that I copied and pasted 'dotnet run --configuration Release WaveFunctionCollapse.csproj' into the Windows 10 command prompt via .Net, but there was an issue (see attached).

![dotnet via command prompt](https://user-images.githubusercontent.com/81527104/166152336-77bb7cdd-9057-4c44-9d92-51cce4a0ed77.png)

What am I doing wrong here?

Thanks for your help.

**Comment by Orangery-DS** [comment]
Sorry about this.  I have since moved all the files from the WFC-master into the same folder as dotnet.exe.  Still an issue though.

![dotnet via command prompt_issue](https://user-images.githubusercontent.com/81527104/166152852-0dc165ec-4d5d-427e-a8f0-7566a14e9e7e.png)

**Comment by mxgmn** [comment]
Replace `net5.0` with `net6.0` in `WaveFunctionCollapse.csproj` and run the command, it should work. In general, you can navigate to any folder using the `cd` command (google how to use it) and run `dotnet run` from there.

**Comment by Orangery-DS** [comment]
Okay - please ignore the last two comments.  I had to run command prompt as administrator and I have also now installed .Net version 5.0, instead of 6.0.4.  So I now have all the example files but still don't know how to get WFC running.

![dotnet 5 0 via command prompt](https://user-images.githubusercontent.com/81527104/166155764-ae0f3eff-21a4-4374-aa7e-7ca9f876db3b.png)

**Comment by Orangery-DS** [comment]
You beat me to it.  So I now have all the example files but how do I get
the WFC to actually run?

Thanks - Dave S.

**Comment by mxgmn** [comment]
It's not example files, it's generated files. You have run it. Example files are in `samples/`.

**Comment by Orangery-DS** [comment]
I see but what if want to edit the input PNG or try out my own?  Also, how
did you create your visuals (watching the patterns self generate)?

At 14;15 in this video https://www.youtube.com/watch?v=fnFj3dOKcIQ by Brian
Bucklew, he shows a quick code example where you can alter the sample,
output size and orientations.  Is this something I can do by altering your
code, in say Wordpad?

Sorry to be a pain.

Regards - Dave S.

**Comment by mxgmn** [comment]
Sure, you can alter the code or alter sample PNGs. Edit `samples.xml` to run with your own samples.
