### ISSUE TITLE
This project is using the name "Wave function collapse" for a process that is not the physics Wave Function Collapse

### ISSUE THREAD

**Issue by KierPrev** [mxgmn/WaveFunctionCollapse#79]
This code doesn't include actual quantum concepts per se, nor wave functions in the complex plane, nor Schrödinger equation, please make the statement clear about not using real physics.

**Comment by magnetomage** [comment]
This algorithm is known as the wave function collapse algorithm. I am sorry that you confused it for a similarly named but entirely different thing in the realm of physics; but this is named correctly.

**Comment by mxgmn** [comment]
This is made clear in the second paragraph.
