### ISSUE TITLE
"Summer" Tileset Origin

### ISSUE THREAD

**Issue by cmcfarla** [mxgmn/WaveFunctionCollapse#8]
> I couldn't find the authors of the summer tileset and will be grateful for information about them.

The tileset you call "Summer" was created by Hermann Hillmann and distributed on sites popular with hobby game developers 10+ years ago. I'm not sure what the official source is any more or how to contact the author; all the old links I knew to it seem to have been taken offline.

Here's an [archive.org copy of the VBExplorer site](https://web.archive.org/web/20050206194145/http://www.vbexplorer.com/VBExplorer/vb_game_downloads.asp) crediting Hermann Hillmann. It has the [~2MB download including winter tiles](https://web.archive.org/web/20020614160418/http://www.vbexplorer.com/VBExplorer/files/tiles.zip) as well. It says:

>  Game Tile Set #1 Excellent free game tile set by Hermann Hillmann(2MB). These and more tiles are included in the Character Pack

**Comment by mxgmn** [comment]
Thank you! I'll update the readme.

**Comment by mxgmn** [comment]
@cmcfarla Thank you! I've updated the readme.
