### ISSUE TITLE
Generate from a pre-defined output image

### ISSUE THREAD

**Issue by SKFrozenCloud** [mxgmn/WaveFunctionCollapse#85]
Hi,

I'm trying to implement a way to give the algorithm a pre-defined output image containing fixed (already put in place) tiles (in overlap mode).

I do not understand the code very well but I have some ideas.

So on this line the output image is created:
https://github.com/mxgmn/WaveFunctionCollapse/blob/a6f79f0f1a4220406220782b71d3fcc73a24a4c2/OverlappingModel.cs#L116
Is it possible to fill the `observed` array with our pre-defined image (before running the algorithm)?
What does the array `observed` do?
Another option would be to put it in inside the `init` or `observer` function.

EDIT:

My use-case is specifying an output image where the border is filled with "water" so that you can guarantee that the algorithm always generates "islands". Same goes with "rooms".

**Comment by mxgmn** [comment]
Hi! To constrain the output, you need to:
1. Ban all unwanted options.
2. Call `Propagate()` to propagate the bans.

For an example, see how I constrain ground pixels in [here](https://github.com/mxgmn/WaveFunctionCollapse/blob/master/Model.cs#L217-L225).

**Comment by SKFrozenCloud** [comment]
Could you just explain the snippet of code you linked so that I can write my own?

**Comment by SKFrozenCloud** [comment]
Thanks, now I understand.
