### ISSUE TITLE
New implementation in Dart

### ISSUE THREAD

**Issue by rick-dalley** [mxgmn/WaveFunctionCollapse#96]
Hello Maxim

Thank you for creating and sharing the Wave Function Collapse algorithm. It has been an inspiration for many, including myself.

I’ve created a Dart implementation of your algorithm to make it accessible to Dart and Flutter developers. You can find it here: [wfc](https://github.com/rick-dalley/wfc).

I was wondering if you’d consider including my implementation in the "Versions" section of your README so others can find it more easily.

Thank you for your time, and I’m happy to provide any additional details if needed.

Best regards,  
Rick Dalley

**Comment by mxgmn** [comment]
Added!

**Comment by rick-dalley** [comment]
Thanks!
